Feature refactor patients allergies update dependencies
systelab/seed-jee pull request #84
Opened 2021-08-06 11:18 UTC by hrcnlz

https://jira-systelab.werfen.com/browse/FXIV-5322
			Training: REST-API testing sessions:
			- Refactor Create Patient, Get Patient
			- Refactor getAllergyData
			- Refactor checkAllergyData

2021-08-06 13:26 UTC, olgapuig requested changes

2021-08-06 13:26 UTC, olgapuig commented on src/test/java/com/systelab/seed/allergy/AllergyResourceTest.java
> +        Response response = given().body(allergy)
Create a unique method for each endpoint that returns a Response (method public Response testCreateAllergy(Allergy) to do not duplicate the code

2021-08-23 09:52 UTC, olgapuig requested changes

2021-08-23 09:52 UTC, olgapuig commented on src/test/java/com/systelab/seed/allergy/AllergyResourceTest.java
> +        if (expected.getName() != null)
The right method is getSymptoms instead of getName

2021-08-23 09:52 UTC, olgapuig commented on src/test/java/com/systelab/seed/allergy/AllergyResourceTest.java
> +        Response response = given().body(allergy)
Here you have some examples for the creation and modification.
 
 ```
private Response doCreateAllergy(Allergy){
    return given().body(allergy).when().post("/allergies/allergy");
  }
  
  private Reponse doModifyAllergy(Allergy, id){
    return given().body(patient)
        .when().put("/patients/" + id);
  }
```

2021-08-25 08:19 UTC, olgapuig reviewed
Good job @Sergioruizlosada and @hrcnlz! I've just added some comments to improve it.

2021-08-25 08:19 UTC, olgapuig commented on src/test/java/com/systelab/seed/allergy/AllergyResourceTest.java
> +    private Response doCreateAllergy(Allergy allergy){
Move this auxiliar method first for clarity purpose.
The intent is to cover all the endpoints for the CRUD (GET, PUT, POST DELETE)

2021-08-25 08:19 UTC, olgapuig commented on src/test/java/com/systelab/seed/patient/PatientResourceTest.java
> +        if (email != null)
This if clause is not needed. The email must be set to the parameter value. Please, remove all.

2021-08-25 08:19 UTC, olgapuig commented on src/test/java/com/systelab/seed/patient/PatientResourceTest.java
>      public void testGetPatientsExcel() {
testGetPatientsExcel() must verify the content of the body. It currently verifies the statusCode

2021-09-22 15:55 UTC, Sergioruizlosada approved these changes

2021-09-29 08:20 UTC, atzurk approved these changes
ok to these upgrades.

2021-09-29 10:40 UTC, atzurk requested changes
I've point two test that are failing at the moment, please correct them, as they prevent this PR from being merged.

2021-09-29 10:40 UTC, atzurk commented on src/test/java/com/systelab/seed/patient/PatientResourceTest.java
> +        TestUtil.checkField("Status Code", 400, statusCode);
This test is failing: you are expecting status 400, but in the last runs the code received is 405.

2021-09-29 10:40 UTC, atzurk commented on src/test/java/com/systelab/seed/patient/PatientResourceTest.java
> +        checkPatientData(patientCreated, finalCheck);
This test is failing: you are compairing the original patient with updated patient. If the update has been done correctly this is never going to be coincident.

2021-09-29 13:15 UTC, atzurk approved these changes

2021-09-29 13:24 UTC, olgapuig approved these changes

2021-09-29 14:53 UTC, merged